name: Build
on:
  push:
    branches: main
  pull_request:
    branches: main
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: Set up JDK 17
        uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4.4.0
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Chmod
        run: chmod +x ./gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1 # v2.11.0
        with:
          arguments: build -x test --scan

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: Set up JDK 17
        uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4.4.0
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'

#      - name: Testspace Setup CLI
#        uses: testspace-com/setup-testspace@ee1482f978eb5010ec27b6f6372904f01f2edd68 # v1.0.6
#        with:
#          domain: ${{ github.repository_owner }}

      - name: Chmod
        run: chmod +x ./gradlew

      - name: Test with Gradle
        uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1 # v2.11.0
        with:
          arguments: test -DiHubTest.failFast=true

      - name: Upload Coverage Reports
        if: ${{ github.repository_owner == 'ihub-pub' }}
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4.6.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

#      - name: Publish Results to Testspace
#        run: testspace */build/test-results/test/*.xml */build/reports/*/test/*.xml

      - name: Upload Test Result
        if: ${{ failure() }}
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: tests
          path: |
            */build/reports/tests
          retention-days: 1

  # publish:
  #   if: ${{ github.event_name == 'push' && github.repository_owner == 'ihub-pub' }}
  #   needs: build
  #   name: Publish to Snapshot Repository
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       java_version: [ 17 ]
  #   steps:
  #     - name: Harden Runner
  #       uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
  #       with:
  #         disable-sudo: true
  #         egress-policy: audit

  #     - name: Checkout repository
  #       uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
  #       with:
  #         fetch-depth: 0
  #     - name: Set up JDK ${{ matrix.java_version }}
  #       uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4.4.0
  #       with:
  #         java-version: ${{ matrix.java_version }}
  #         distribution: 'adopt'
  #         cache: 'gradle'

  #     - name: Publish to Snapshot Repository
  #       uses: ihub-pub/bot/publish@ab2556b0345738c3f23a53d6253eede9ae3f4145 # v2.0.3
  #       with:
  #         repoUsername: ${{ secrets.REPO_USERNAME }}
  #         repoPassword: ${{ secrets.REPO_PASSWORD }}
  #         useInferringVersion: true
