name: Gradle Dependency Graph
on:
  schedule:
    - cron: '0 */6 * * *'
  push:
    branches: main

permissions:
  contents: read

jobs:
  gradle-action-detection:
    if: ${{ github.repository_owner == 'ihub-pub' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - name: Set up JDK 17
        uses: actions/setup-java@main
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Setup Gradle to generate and submit dependency graphs
        uses: gradle/gradle-build-action@v3.3.2
        with:
          dependency-graph: generate-and-submit
          arguments: dependencies
