name: Build
on:
  push:
    branches: main
  pull_request:
    branches: main
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up JDK 17
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Chmod
        run: chmod +x ./gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1 # v2.11.0
        with:
          arguments: build -x test --scan

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up JDK 17
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'

#      - name: Testspace Setup CLI
#        uses: testspace-com/setup-testspace@ee1482f978eb5010ec27b6f6372904f01f2edd68 # v1.0.6
#        with:
#          domain: ${{ github.repository_owner }}

      - name: Chmod
        run: chmod +x ./gradlew

      - name: Test with Gradle
        uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1 # v2.11.0
        with:
          arguments: test -DiHubTest.failFast=true

      - name: Upload Coverage Reports
        if: ${{ github.repository_owner == 'ihub-pub' }}
        uses: codecov/codecov-action@0565863a31f2c772f9f0395002a31e3f06189574 # v5.4.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

#      - name: Publish Results to Testspace
#        run: testspace */build/test-results/test/*.xml */build/reports/*/test/*.xml

      - name: Upload Test Result
        if: ${{ failure() }}
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: tests
          path: |
            */build/reports/tests
          retention-days: 1

  # publish:
  #   if: ${{ github.event_name == 'push' && github.repository_owner == 'ihub-pub' }}
  #   needs: build
  #   name: Publish to Snapshot Repository
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       java_version: [ 17 ]
  #   steps:
  #     - name: Harden Runner
  #       uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
  #       with:
  #         disable-sudo: true
  #         egress-policy: audit

  #     - name: Checkout repository
  #       uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
  #       with:
  #         fetch-depth: 0
  #     - name: Set up JDK ${{ matrix.java_version }}
  #       uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
  #       with:
  #         java-version: ${{ matrix.java_version }}
  #         distribution: 'adopt'
  #         cache: 'gradle'

  #     - name: Publish to Snapshot Repository
  #       uses: ihub-pub/bot/publish@ab2556b0345738c3f23a53d6253eede9ae3f4145 # v2.0.3
  #       with:
  #         repoUsername: ${{ secrets.REPO_USERNAME }}
  #         repoPassword: ${{ secrets.REPO_PASSWORD }}
  #         useInferringVersion: true
